import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleAnalytics } from "@next/third-parties/google";
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SuperINTRO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <GoogleTagManager gtmId="G-XZVM91TWBZ" /> */}
      <body className={cn(inter.className, 'bg-black text-gray-300')}>{children}</body>
      <GoogleAnalytics gaId="G-XZVM91TWBZ" />
    </html>
  );
}
