import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleTagManager } from "@next/third-parties/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SuperINTRO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="G-XZVM91TWBZ" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
